'use client';

import { useChat } from 'ai/react';
import { useEffect, useRef, useState } from 'react';
import { useOnlineStatus } from '@/hooks/useOnlineStatus';
import Button from '@/components/ui/Button';
import { STORY_INITIAL_MESSAGE } from '@/lib/story-prompt';

export default function StoryPage() {
  const isOnline = useOnlineStatus();
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const [showSendButton, setShowSendButton] = useState(false);
  const [emailSent, setEmailSent] = useState(false);
  const [isSendingEmail, setIsSendingEmail] = useState(false);

  const { messages, input, handleInputChange, handleSubmit, isLoading } = useChat({
    api: '/api/story-chat',
    initialMessages: [
      {
        id: 'welcome',
        role: 'assistant',
        content: STORY_INITIAL_MESSAGE,
      },
    ],
    onFinish: (message) => {
      // Show send button after enough conversation or when AI signals wrap-up
      if (messages.length >= 10 ||
          message.content.toLowerCase().includes('send my story') ||
          message.content.toLowerCase().includes('ready to send')) {
        setShowSendButton(true);
      }
    },
  });

  // Auto-scroll to bottom
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Show send button after meaningful conversation
  useEffect(() => {
    if (messages.length >= 12) {
      setShowSendButton(true);
    }
  }, [messages.length]);

  const compileStoryFromMessages = (): string => {
    let story = "JENNIFER'S STORY\n";
    story += "================\n";
    story += `Collected on ${new Date().toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })}\n\n`;

    story += "CONVERSATION\n";
    story += "------------\n\n";

    for (const msg of messages) {
      if (msg.role === 'assistant') {
        story += `Interviewer: ${msg.content}\n\n`;
      } else {
        story += `Jennifer: ${msg.content}\n\n`;
      }
    }

    story += "\n========================================\n";
    story += "SUMMARY FOR HELPER\n";
    story += "========================================\n\n";

    // Extract key info from Jennifer's responses
    const jenniferMessages = messages.filter(m => m.role === 'user').map(m => m.content);
    const allText = jenniferMessages.join(' ').toLowerCase();

    story += "KEY INFORMATION SHARED:\n";
    story += "- Review the conversation above for Jennifer's full story\n";
    story += "- Pay special attention to her Falcons memories and what they mean to her\n";
    story += "- Note any specific needs or requests she mentioned\n\n";

    story += "RECOMMENDED NEXT STEPS:\n";
    story += "1. Call 211 to get Jennifer connected with a SOAR worker\n";
    story += "2. Apply for Presumptive SSI (she qualifies due to leg amputation)\n";
    story += "3. Get Grady Card for free medical care: 404-616-1000\n";
    story += "4. Apply for expedited SNAP at gateway.ga.gov\n\n";

    story += "ATLANTA FALCONS OUTREACH:\n";
    story += "- Community Relations: community@atlantafalcons.com\n";
    story += "- Atlanta Falcons: (470) 341-4500\n";
    story += "- Arthur Blank Family Foundation\n\n";

    story += "---\n";
    story += "Generated by Jennifer's Assistant\n";

    return story;
  };

  const handleSendEmail = async () => {
    setIsSendingEmail(true);
    try {
      const storyText = compileStoryFromMessages();

      const recipient = 'c.parker3@me.com';
      const subject = encodeURIComponent("🏈 Jennifer's Story - Please Read");
      const body = encodeURIComponent(storyText);

      window.location.href = `mailto:${recipient}?subject=${subject}&body=${body}`;

      setEmailSent(true);
    } catch (error) {
      console.error('Error sending email:', error);
    }
    setIsSendingEmail(false);
  };

  const onSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!input.trim() || isLoading) return;
    handleSubmit(e);
  };

  return (
    <div className="flex flex-col h-[calc(100vh-140px)]">
      {/* Header */}
      <div className="px-4 py-3 border-b border-falcons-silver/10">
        <h1 className="font-display text-lg font-bold text-white">Share Your Story 🏈</h1>
        <p className="text-sm text-falcons-silver">
          {messages.length <= 2
            ? "Take your time - I'm here to listen"
            : `${messages.filter(m => m.role === 'user').length} messages shared`}
        </p>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-4 py-4 space-y-4 scrollbar-hide">
        {messages.map((message) => (
          <div
            key={message.id}
            className={`max-w-[90%] ${message.role === 'assistant' ? 'self-start' : 'self-end ml-auto'}`}
          >
            <div className={message.role === 'assistant' ? 'message-ai' : 'message-user'}>
              <div className="text-base leading-relaxed whitespace-pre-wrap">
                {message.content}
              </div>
            </div>
            <div className={`text-xs text-falcons-silver/60 mt-1 ${message.role === 'assistant' ? 'text-left' : 'text-right'}`}>
              {message.role === 'assistant' ? 'Interviewer' : 'Jennifer'}
            </div>
          </div>
        ))}

        {/* Loading indicator */}
        {isLoading && (
          <div className="self-start max-w-[90%]">
            <div className="message-ai">
              <div className="flex items-center gap-2">
                <div className="w-2 h-2 bg-falcons-red rounded-full animate-bounce" />
                <div className="w-2 h-2 bg-falcons-red rounded-full animate-bounce" style={{ animationDelay: '0.1s' }} />
                <div className="w-2 h-2 bg-falcons-red rounded-full animate-bounce" style={{ animationDelay: '0.2s' }} />
              </div>
            </div>
          </div>
        )}

        {/* Send Story Button */}
        {showSendButton && !emailSent && !isLoading && (
          <div className="pt-4 space-y-3">
            <div className="card p-4 text-center">
              <p className="text-sm text-falcons-silver mb-3">
                Ready to share your story?
              </p>
              <Button onClick={handleSendEmail} disabled={isSendingEmail}>
                {isSendingEmail ? 'Opening email...' : '📧 Send My Story'}
              </Button>
            </div>
          </div>
        )}

        {/* Email sent confirmation */}
        {emailSent && (
          <div className="card p-4 text-center bg-success/20 border-success">
            <p className="text-success font-semibold">Story ready to send!</p>
            <p className="text-sm text-falcons-silver mt-1">
              Your email app should be open. Just tap Send!
            </p>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="border-t border-falcons-silver/10 p-4 bg-bg-dark/95 backdrop-blur-sm">
        {!isOnline && (
          <div className="mb-3 p-3 bg-warning/20 rounded-card text-warning text-sm text-center">
            You&apos;re offline. Story sharing needs internet.
          </div>
        )}

        <form onSubmit={onSubmit} className="flex gap-3">
          <textarea
            value={input}
            onChange={handleInputChange}
            placeholder="Share your thoughts..."
            disabled={!isOnline || isLoading}
            rows={2}
            className="input-field flex-1 resize-none"
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                onSubmit(e as unknown as React.FormEvent<HTMLFormElement>);
              }
            }}
          />
          <button
            type="submit"
            disabled={!input.trim() || isLoading || !isOnline}
            className="w-14 h-14 bg-falcons-red rounded-card flex items-center justify-center disabled:opacity-50 transition-opacity self-end"
          >
            <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
            </svg>
          </button>
        </form>

        {/* Show send button hint after some messages */}
        {messages.length >= 6 && messages.length < 12 && !showSendButton && (
          <p className="text-xs text-falcons-silver/50 text-center mt-2">
            Keep sharing - the &quot;Send&quot; button will appear when ready
          </p>
        )}
      </div>
    </div>
  );
}
