'use client';

import { useChat } from 'ai/react';
import { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import { useOnlineStatus } from '@/hooks/useOnlineStatus';
import Button from '@/components/ui/Button';
import { STORY_INITIAL_MESSAGE } from '@/lib/story-prompt';

export default function StoryPage() {
  const isOnline = useOnlineStatus();
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const [showSendButton, setShowSendButton] = useState(false);
  const [emailSent, setEmailSent] = useState(false);
  const [isSendingEmail, setIsSendingEmail] = useState(false);

  const { messages, input, handleInputChange, handleSubmit, isLoading } = useChat({
    api: '/api/story-chat',
    initialMessages: [
      {
        id: 'welcome',
        role: 'assistant',
        content: STORY_INITIAL_MESSAGE,
      },
    ],
    onFinish: (message) => {
      // Show send button after enough conversation or when AI signals wrap-up
      if (messages.length >= 10 ||
          message.content.toLowerCase().includes('send my story') ||
          message.content.toLowerCase().includes('ready to send')) {
        setShowSendButton(true);
      }
    },
  });

  // Auto-scroll to bottom
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Show send button after meaningful conversation
  useEffect(() => {
    if (messages.length >= 12) {
      setShowSendButton(true);
    }
  }, [messages.length]);

  const compileStoryFromMessages = (): string => {
    let story = "JENNIFER'S STORY\n";
    story += "================\n";
    story += `Collected on ${new Date().toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })}\n\n`;

    story += "CONVERSATION\n";
    story += "------------\n\n";

    for (const msg of messages) {
      if (msg.role === 'assistant') {
        story += `Interviewer: ${msg.content}\n\n`;
      } else {
        story += `Jennifer: ${msg.content}\n\n`;
      }
    }

    story += "\n========================================\n";
    story += "SUMMARY FOR HELPER\n";
    story += "========================================\n\n";

    story += "KEY INFORMATION SHARED:\n";
    story += "- Review the conversation above for Jennifer's full story\n";
    story += "- Pay special attention to her Falcons memories and what they mean to her\n";
    story += "- Note any specific needs or requests she mentioned\n\n";

    story += "RECOMMENDED NEXT STEPS:\n";
    story += "1. Call 211 to get Jennifer connected with a SOAR worker\n";
    story += "2. Apply for Presumptive SSI (she qualifies due to leg amputation)\n";
    story += "3. Get Grady Card for free medical care: 404-616-1000\n";
    story += "4. Apply for expedited SNAP at gateway.ga.gov\n\n";

    story += "ATLANTA FALCONS OUTREACH:\n";
    story += "- Community Relations: community@atlantafalcons.com\n";
    story += "- Atlanta Falcons: (470) 341-4500\n";
    story += "- Arthur Blank Family Foundation\n\n";

    story += "---\n";
    story += "Generated by Jennifer's Assistant\n";

    return story;
  };

  const handleSendEmail = async () => {
    setIsSendingEmail(true);
    try {
      const storyText = compileStoryFromMessages();

      const recipient = 'c.parker3@me.com';
      const subject = encodeURIComponent("Jennifer's Story - Please Read");
      const body = encodeURIComponent(storyText);

      window.location.href = `mailto:${recipient}?subject=${subject}&body=${body}`;

      setEmailSent(true);
    } catch (error) {
      console.error('Error sending email:', error);
    }
    setIsSendingEmail(false);
  };

  const onSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!input.trim() || isLoading) return;
    handleSubmit(e);
  };

  return (
    <div className="flex flex-col h-[calc(100vh-140px)]">
      {/* Hero Section with Player Image */}
      <div className="relative h-48 overflow-hidden">
        <Image
          src="/images/falcons/matt-ryan-julio-jones.jpg"
          alt="Matt Ryan and Julio Jones celebrating"
          fill
          className="object-cover object-top"
          priority
        />
        <div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-[var(--bg-primary)]" />
        <div className="absolute bottom-0 left-0 right-0 p-4">
          <h1 className="font-display text-2xl font-bold text-white drop-shadow-lg">
            Share Your Story
          </h1>
          <p className="text-white/90 text-sm drop-shadow">
            {messages.length <= 2
              ? "Take your time - I'm here to listen"
              : `${messages.filter(m => m.role === 'user').length} messages shared`}
          </p>
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-4 py-4 space-y-4 scrollbar-hide">
        {messages.map((message, index) => (
          <div
            key={message.id}
            className={`max-w-[90%] animate-slide-up ${message.role === 'assistant' ? 'self-start' : 'self-end ml-auto'}`}
            style={{ animationDelay: `${index * 0.05}s` }}
          >
            <div className={message.role === 'assistant' ? 'message-ai' : 'message-user'}>
              <div className="text-base leading-relaxed whitespace-pre-wrap">
                {message.content}
              </div>
            </div>
            <div className={`text-xs text-muted mt-2 ${message.role === 'assistant' ? 'text-left' : 'text-right'}`}>
              {message.role === 'assistant' ? 'Interviewer' : 'Jennifer'}
            </div>
          </div>
        ))}

        {/* Loading indicator */}
        {isLoading && (
          <div className="self-start max-w-[90%] animate-fade-in">
            <div className="message-ai">
              <div className="flex items-center gap-3">
                <div className="w-2.5 h-2.5 bg-falcons-red rounded-full animate-bounce" />
                <div className="w-2.5 h-2.5 bg-falcons-red rounded-full animate-bounce" style={{ animationDelay: '0.15s' }} />
                <div className="w-2.5 h-2.5 bg-falcons-red rounded-full animate-bounce" style={{ animationDelay: '0.3s' }} />
              </div>
            </div>
          </div>
        )}

        {/* Send Story Button */}
        {showSendButton && !emailSent && !isLoading && (
          <div className="pt-4 space-y-3 animate-slide-up">
            <div className="card-elevated p-5 text-center">
              <div className="w-16 h-16 mx-auto mb-4 rounded-full flex items-center justify-center" style={{ background: 'linear-gradient(135deg, var(--falcons-red) 0%, var(--falcons-red-dark) 100%)' }}>
                <span className="text-3xl">📧</span>
              </div>
              <p className="text-secondary mb-4">
                Ready to share your story with someone who can help?
              </p>
              <Button onClick={handleSendEmail} disabled={isSendingEmail}>
                {isSendingEmail ? 'Opening email...' : 'Send My Story'}
              </Button>
            </div>
          </div>
        )}

        {/* Email sent confirmation */}
        {emailSent && (
          <div className="card-elevated p-5 text-center animate-slide-up" style={{ borderColor: 'var(--success)' }}>
            <div className="w-16 h-16 mx-auto mb-4 rounded-full flex items-center justify-center bg-success/20">
              <span className="text-3xl">✓</span>
            </div>
            <p className="font-semibold text-success">Story ready to send!</p>
            <p className="text-sm text-secondary mt-2">
              Your email app should be open. Just tap Send!
            </p>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="border-t border-[var(--border-color)] p-4 glass">
        {!isOnline && (
          <div className="mb-3 p-4 rounded-card bg-warning/10 border border-warning/30 text-center">
            <span className="text-warning font-medium">You&apos;re offline</span>
            <span className="text-secondary block text-sm mt-1">Story sharing needs internet</span>
          </div>
        )}

        <form onSubmit={onSubmit} className="flex gap-3">
          <textarea
            value={input}
            onChange={handleInputChange}
            placeholder="Share your thoughts..."
            disabled={!isOnline || isLoading}
            rows={2}
            className="input-field flex-1 resize-none"
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                onSubmit(e as unknown as React.FormEvent<HTMLFormElement>);
              }
            }}
          />
          <button
            type="submit"
            disabled={!input.trim() || isLoading || !isOnline}
            className="w-14 h-14 rounded-card flex items-center justify-center disabled:opacity-50 transition-all duration-200 hover:shadow-glow-sm active:scale-95 self-end"
            style={{
              background: 'linear-gradient(135deg, var(--falcons-red) 0%, var(--falcons-red-dark) 100%)',
            }}
          >
            <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
            </svg>
          </button>
        </form>

        {/* Show send button hint after some messages */}
        {messages.length >= 6 && messages.length < 12 && !showSendButton && (
          <p className="text-xs text-muted text-center mt-3">
            Keep sharing - the &quot;Send&quot; button will appear when ready
          </p>
        )}
      </div>
    </div>
  );
}
